// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16oRjWCuTvyhSk0D829DkDrUwI_NRFGQ',
    appId: '1:20597315271:web:cb44ac17c4c6b5564b90e2',
    messagingSenderId: '20597315271',
    projectId: 'koko-chat-6c914',
    authDomain: 'koko-chat-6c914.firebaseapp.com',
    storageBucket: 'koko-chat-6c914.appspot.com',
    measurementId: 'G-LKXJEXZB4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqv58l-pf49xP_lrmLJvYOEtCnv_JRdOM',
    appId: '1:20597315271:android:ff4f9efb9963a44d4b90e2',
    messagingSenderId: '20597315271',
    projectId: 'koko-chat-6c914',
    storageBucket: 'koko-chat-6c914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtYtirQewKlPwgCB61iiPKz_GGsT43qVk',
    appId: '1:20597315271:ios:94ad60bfb08523214b90e2',
    messagingSenderId: '20597315271',
    projectId: 'koko-chat-6c914',
    storageBucket: 'koko-chat-6c914.appspot.com',
    iosBundleId: 'com.example.kokoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC16oRjWCuTvyhSk0D829DkDrUwI_NRFGQ',
    appId: '1:20597315271:web:01b1f75695922f0f4b90e2',
    messagingSenderId: '20597315271',
    projectId: 'koko-chat-6c914',
    authDomain: 'koko-chat-6c914.firebaseapp.com',
    storageBucket: 'koko-chat-6c914.appspot.com',
    measurementId: 'G-0662YMGB9D',
  );
}
